import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/sharedModules/header/page";
import Footer from "@/sharedModules/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
<div
        className="fixed inset-0 bg-fixed"
        style={{
          backgroundImage: `url("https://images.pexels.com/photos/3780104/pexels-photo-3780104.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          zIndex: -1,
          opacity: 2,  // Optional: to make it less dominant
        }}
      />
      <body className={inter.className}>
        {/* Background Image */}
        
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
